### ISSUE TITLE
Non-positive count value causes infinite loop

### ISSUE THREAD

**Issue by danielkov** [kubarium/react-nbsp#3]
Because of this:
```js
do {
        space = space.concat('\u00A0')
    } while (--count);
```
If the value of count is not positive, the break condition will never be reached and therefore will cause an infinite loop.

[Related CodeSandbox](https://codesandbox.io/s/wonderful-raman-nrjl5).

**Comment by kubarium** [comment]
My man, be a better monkey :) I'm not sure what you hoped to achieve by putting a negative number but it should be fixed now.

**Comment by danielkov** [comment]
I'm sure being called a monkey is the perfect reward for someone looking to contribute to open source software. I'm sure you realise that whatever is supplied to you component may be a result of a calculation, which may result in a negative value or even `0`, which still causes an infinite loop by the way. I would expect this component to render `null` when the value is below `1` by the way.

**Comment by kubarium** [comment]
I apologize if you took offence by my reference. It was just a joke based on evolution that we are just more capable chimps, that's all. Sorry again. Without body language, it's hard to convey humour over text.

As far as the code goes, I understand the value might be fed through a calculation. I'll look into it at my earliest convenience. Thank you for pointing it out. In the meantime, maybe you could sanitize the value you are feeding into this component if that's the case for you.
